// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "58cbd89fd8df298a2f4c690a94262881"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"2576b02ce4cf56084d3ef2b6714559cd": "1f8b08000000000000ff548c31aec23010446bcf295629be922f487a6a6a1a4ee0388bb120b6b55e835094bb53100ada99f75eb6ee663d53617904c740987312a516a6f141af75ec5d9a87a02c21faa1d4b1381bf7f95e7d8843d124d673830ed057663a7f325454aa535a6026daa0fe681356e052a3a3133fdb9fa7a3ffafbbc0086b95487fdbb4c098e940d30e66c58a77000000ffff7abf77f9b4000000",
		"4adc860d2724dbd31a7da30e60cd476c": "1f8b08000000000000ff648f314ec4301045ebcc2946ae9255484e404f45b1141488226b0d598b8d6d66c641c8f2dd91376e1095a5ef3fefe9c7c57e2e2be1553502b82d0656eca133394fcfcb46a5cc42bc3b4b061011cdeaf49a2e930ddbec94d8f975967411bbf887784babf33387a4c4adee49e7ca363000ec0b57b6ec164f8d3abd1c6ffdfe48dee2f97eddcbbfc6806fef077a7a528d980fd0230a744c9ad8ff2d64e8ba6c9444cd88f2234a5b19a12b509ae9c8faeffbf6e94c1283177ae53a6b44c653cbbf12890e48cc81abb5c9bcbb41f90d0000ffff3d3fccb43f010000",
		"8cfce0dcb361a8f7da25bc989bab49b8": "1f8b08000000000000ff9492c16e13311086cf99a718ed01d95170e0017a8120c1a11502894bd583e39d6eaceedaabf1ec02b2f6dd919b649b1451d2933dfefdcfff6934bd750fb621ecac0f00beeb230b2a58548d97ddb0352e766b2fc43e34eb346c93b3e16ddf0e8d0feb24916d43d5459f390e425c01226295b3b9b11d4dd37a27d2fff5988847ef9e374ebbd8a7feb1774dce77b6ad40038c9631f188cb83cb7cdf9f00f2bb27ccd95cc7fa636b539a264cc28313ccb0a8f1806f3636c204703f048737f453695c9e9b322c9864e0806fce843ccd3e659f99347e095e3636aab3205d9a15da2b3ce296486b6a0d0b6b6abcc2ba5cae7dc35648e9ff257c16e995c6dbbbfd7c4da99f78cb74cdb74745251e5fecf695a3a3943efd12f62179a7b66d740fb83cd27f28e50ae9a83f29b3658534529084b777b3561e341273e4934106df5ec252ccffe228da09432957784f8487e5309bfdf9eaf079f6985ffaf68338f918942e4be543731250bd33ef2b98e04f000000ffffb99ec6d35c030000",
		"901dee514c4b917fa63490110021898e": "1f8b08000000000000ff2a484cce4e4c4f55c8cd4f49cde1e22aa92c4855a8aed6f3cd4f71ce492c2eaead55282e292a4d2e51a8e6aae502040000ffffcb815bad2d000000",
		"9040efce6e173ddbe5aa65b5ee616485": "1f8b08000000000000ff54ca3b6ec4201000d03a730acaa4f0008ea2dc62ef80f1188f161676f83496efbe923bd7efa5bcf648ea38f0e1129d2740c8caa2fd05107a771652dff015b8ed7d419f930e79e9dbe662d6c5f9a7e831ab31e33fdadbe246c2afa06b5f6a13d768728527295e0d8306ff6eb9eeb9d472fd953c2717d5b038a3b9ad2e9b1ba47de44b0d1af801f8040000ffffaeeda95ec0000000",
		"e2180af47102e9758aad571e6e107783": "1f8b08000000000000ff2a484cce4e4c4f554849cce7e24a2bcd4b5670c9d7d0ace6e2aa05040000ffffd318594c1a000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("all", "./templates/plugin")
		b.SetResolver("dao/dao.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "e2180af47102e9758aad571e6e107783"})
		b.SetResolver("go.mod.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "9040efce6e173ddbe5aa65b5ee616485"})
		b.SetResolver("http/http.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "4adc860d2724dbd31a7da30e60cd476c"})
		b.SetResolver("main.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "8cfce0dcb361a8f7da25bc989bab49b8"})
		b.SetResolver("model/model.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "901dee514c4b917fa63490110021898e"})
		b.SetResolver("service/service.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "2576b02ce4cf56084d3ef2b6714559cd"})
	}()

	return nil
}()
