// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "58cbd89fd8df298a2f4c690a94262881"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"2576b02ce4cf56084d3ef2b6714559cd": "1f8b08000000000000ff548c31aec23010446bcf295629be922f487a6a6a1a4ee0388bb120b6b55e835094bb53100ada99f75eb6ee663d53617904c740987312a516a6f141af75ec5d9a87a02c21faa1d4b1381bf7f95e7d8843d124d673830ed057663a7f325454aa535a6026daa0fe681356e052a3a3133fdb9fa7a3ffafbbc0086b95487fdbb4c098e940d30e66c58a77000000ffff7abf77f9b4000000",
		"4adc860d2724dbd31a7da30e60cd476c": "1f8b08000000000000ff6490314ff4300c86e7fa575899ee4efdd25ff0ed2c20740c0c8821174c1b714d82ed14a128ff1df5da0531457af3fa796467e73fdc4838a9668030e7c48a07e84cadf63ebd3d3a9d5aabd53eb8995a1b8478099e0c20229a31e8542ed6a779084a1ce23848b98877f15fbe9631c4815351e2bd1e4987d563e008b0385e3db2783ced54fbb4bdebf77b891ecfb7e983fc691cf1e57543db3bd58c7503fd47818e490bc7df850a5d578d92a8e951be45696e3d740dda6edab2c3d7ed0ef64c9253147ae675ad1e194f7bfe5948f488c49c78b5eeb218aed07e020000ffff332ff2ab4b010000",
		"8cfce0dcb361a8f7da25bc989bab49b8": "1f8b08000000000000ff9c93c16edb300c86cfd153103e0c5690c9db03f4b03503d6438a604577298a4091159ba82d1994e46e30fcee83ecd44d5a24ed7ab225f1e747fda41aa91e64a1a1ebc4b5ac75df33867563c943ca0000024252a02fc356285b67e835a1293217b64e49f3b9a942812661b3b78332e72dc942bf2f986cf09a92a186a4ebc4cae66be9cbbe9f0acd4aef9bb3014e538bea25d095b671cdc0ccb5c25a5609e38cb592c0510bf3bd4adc8c5fc6fcdf66f06765f3cb4a3ad7f7e03c05e5a163b31cf6d7124b6959cfd82e1805d7fa31e5303f16756c46da0732f0e9e8a0eb275d2a5f88385c19f44b69d323108fc962b517f0546e444a9173369322870bc8e3cf0a0b925ea7fc2dc24fef9b94c3ddfde8bb88ebe77aa3d3e2d770923a6acf665b9355dab91f7f3ca171a8d20dcc9f2aff5e59f5b080839d296cb181bbfb69b7d5c673d044960e6c3358bd871cc5afa987d018b1d8c0befd62397eff1b38b90b5d0ccb32580fc3eba0d5e4d09a93cadfe379cae324a1290e98c917f135d9a7fb86b583db2b50d6ecb03899ed162fadd9c5810b28c60516afaf916570131f19e156c3643c3ca22fc1355aa1aca0b679a8f449d2a47f6e2f1ffa162fd10d6ff11c33faee3e081cba7a0ef62f0000ffffbb27e82eca040000",
		"901dee514c4b917fa63490110021898e": "1f8b08000000000000ff2a484cce4e4c4f55c8cd4f49cde1e22aa92c4855a8aed6f3cd4f71ce492c2eaead55282e292a4d2e51a8e6aae502040000ffffcb815bad2d000000",
		"e2180af47102e9758aad571e6e107783": "1f8b08000000000000ff2a484cce4e4c4f554849cce7e24a2bcd4b5670c9d7d0ace6e2aa05040000ffffd318594c1a000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("all", "./templates/plugin")
		b.SetResolver("dao/dao.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "e2180af47102e9758aad571e6e107783"})
		b.SetResolver("http/http.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "4adc860d2724dbd31a7da30e60cd476c"})
		b.SetResolver("main.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "8cfce0dcb361a8f7da25bc989bab49b8"})
		b.SetResolver("model/model.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "901dee514c4b917fa63490110021898e"})
		b.SetResolver("service/service.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "2576b02ce4cf56084d3ef2b6714559cd"})
	}()

	return nil
}()
